# Generated by Django 4.0.2 on 2022-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_class_class_date_remove_course_prev_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num',
            field=models.CharField(max_length=50, unique=True, verbose_name='Course Number'),
        ),
    ]
