# Generated by Django 4.0.2 on 2022-03-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_intent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_msg_text', models.CharField(max_length=50, verbose_name='Question Text')),
            ],
            options={
                'verbose_name': 'User Massage (Example)',
                'verbose_name_plural': 'User Massages (Examples)',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='intent',
            name='story',
        ),
        migrations.RemoveField(
            model_name='intent',
            name='title',
        ),
        migrations.AddField(
            model_name='intent',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Intent Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.AddField(
            model_name='usermsg',
            name='intent_of_example',
            field=models.ManyToManyField(related_name='Intents', to='bot.Intent'),
        ),
        migrations.AddField(
            model_name='answer',
            name='example',
            field=models.ManyToManyField(related_name='example', to='bot.Usermsg'),
        ),
    ]
