# Generated by Django 4.0.2 on 2022-03-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_usermsg_remove_answer_question_remove_intent_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='example',
            field=models.ManyToManyField(related_name='examples', to='bot.Usermsg'),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='user_msg_text',
            field=models.CharField(max_length=50, verbose_name='Text of User Massage (Example)'),
        ),
    ]
