# Generated by Django 4.0.2 on 2022-03-15 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_answer_example_alter_usermsg_user_msg_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.story'),
        ),
    ]
