# Generated by Django 4.0.2 on 2022-03-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_answer_example_answer_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermsg',
            old_name='intent_of_example',
            new_name='example_of_intent',
        ),
    ]
